### ISSUE TITLE
Streams "underneath" screen notch on MacBook Pro

### ISSUE THREAD

**Issue by andypiper** [b123400/TootRain#2]
The text streams from right to left across the screen, and goes behind/under the notch. It would be nice to have the option to have the stream scroll along underneath the menubar to avoid the notch.

**Comment by b123400** [comment]
The window level setting "Above All Windows" should be exactly that, doesn't it work?

![Screenshot 2023-06-03 at 16 11 32](https://github.com/b123400/TootRain/assets/127193/01b287b9-d260-4f82-8432-446f4905b2b6)

**Comment by andypiper** [comment]
Oh! I understood that to mean that it would be at the top “layer” of the display over everything else, rather than behind any windows. I will take another look.

**Comment by andypiper** [comment]
This was my mistake, although a suggestion might be to modify the option to say "below menubar" or have a hover tip to indicate that this is what "Above all windows" means. Thanks.
