### ISSUE TITLE
Does not work with some Mastodon instances

### ISSUE THREAD

**Issue by andypiper** [b123400/TootRain#3]
I have been able to connect to `https://social.lol` (the app connects and content streams), but my main account is on `https://macaw.social`. When I connect to that instance, nothing seems to happen.

If I run the binary from the command line, I see this message:

`
2023-06-02 23:46:14.455 TootRain[97983:13190183] ws str: (null), error: Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSErrorFailingURLStringKey=http://macaw.social/api/v1/streaming/?access_token=[removed]&stream=public, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLKey=http://macaw.social/api/v1/streaming/?access_token=[removed]&stream=public}
`

It looks like this is trying to use `http://macaw.social` and I guess it would need to use `https://macaw.social`?

**Comment by andypiper** [comment]
Hmm. It could be due to the server configuration here - I'm not sure if the redirect from http->https is working on this specific instance.

**Comment by b123400** [comment]
When you log into your account, did you use `https://` for the instance URL?
If you entered `http://macaw.social` TootRain would connect to the stream with http, which doesn't work due to ATS.

**Comment by andypiper** [comment]
I did use `https` yes - I’ve also tried removing the preferences (I think… this is the AppStore version so I deleted the container data) and signing in again just to confirm it, but it still seems to be getting `http` from somewhere.

**Comment by b123400** [comment]
Thanks for the confirmation.
Since the app is already trying to connect to the stream endpoint, I assume all the previous API calls (e.g. OAuth and account verification) are all fine with `https`.
Perhaps there's a configuration problem with websocket on Macaw's side?
I tried to register an account but it's only for current/previous twitter employees

**Comment by andypiper** [comment]
Well now I tried reinstalling from the App Store and the config still seems to be there, so I am not certain where it is saving that. However yes, it could be a configuration on the server so I will talk to the admin as well. Thanks.

**Comment by andypiper** [comment]
OK, definitely seems to be a specific instance issue, closing.
