### ISSUE TITLE
It works BUT Does NOT show up

### ISSUE THREAD

**Issue by mengxin10824** [b123400/TootRain#4]
I'm encountering an issue with the display of timeline in the social media app. Currently, the messages are not visible on the screen unless I hover over them with the mouse cursor. 

Additional Information:
- I have tried refreshing the page and restarting the app, but the issue persists.
- Other interactive features of the app, such as hover effects on other elements, seem to be working fine.
- I'm using the latest version of the app on macOS 14.0.

![Video](https://github.com/b123400/TootRain/assets/47906112/5d471b45-d402-4114-9867-8159daee3499)

Please let me know if you need any further information to investigate this issue. Thank you for your attention to this matter.

**Comment by b123400** [comment]
Hello, thank you for reporting.
It works well on my macOS 13.4.1 (22F82), and macOS 14 is still in beta.
Unfortunately I don't have any spare machine to try the beta out, I'll see if I can install it in a virtual machine, but can't really promise anything.

**Comment by mengxin10824** [comment]
Thank you for reading my issue. honestly I didn't think you were still running the program consistently. In the meantime, I'm trying to run it with a VM to check if it's my beta system fault.

I will report back later if ithat is the problem.

Thanks again for creating such an interesting application, I will recommend this to others after that!

**Comment by mengxin10824** [comment]
Well I tested it and found the reason, and you guessed it, only beta versions of Mac OS  have this problem...
<img width="912" alt="image" src="https://github.com/b123400/TootRain/assets/47906112/474ffa2e-d090-47af-aba5-21eaf4824aea">

**Comment by b123400** [comment]
It looks like the issue [still exists](https://is-he.re/notice/AaCJcx6mob8iSpkEMq) on the released version

**Comment by mengxin10824** [comment]
Yes 🥹

**Comment by b123400** [comment]
I've fixed the issue and released 1.7.2.
It should be available on AppStore soon, you also can download it directly: https://b123400.net/tootrain/updates/TootRain-1.7.2.zip
